"""
Query engine for querying indexed documents using RAG-Anything.
"""
from typing import Optional
from gdd_rag_backbone.rag_backend.indexing import get_rag_instance_for_doc


async def ask_question(
    doc_id: str,
    query: str,
    *,
    mode: str = "mix",
    debug: bool = False,
    **query_kwargs
) -> str:
    """
    Ask a question about an indexed document using RAG.
    
    Args:
        doc_id: Document ID to query
        query: Question or query text
        mode: Query mode - "local", "global", "hybrid", "naive", "mix", "bypass"
              (default: "mix")
        debug: If True, print debug information about retrieved chunks
        **query_kwargs: Additional query parameters (vlm_enhanced, etc.)
    
    Returns:
        Answer string generated by the RAG system
    
    Raises:
        ValueError: If doc_id is not found or RAG instance is not available
    """
    if not doc_id:
        raise ValueError("doc_id cannot be empty")
    
    if not query:
        raise ValueError("query cannot be empty")
    
    # Get the RAG instance for this document
    rag = get_rag_instance_for_doc(doc_id)
    
    if rag is None:
        raise ValueError(
            f"No RAG instance found for doc_id: {doc_id}. "
            "Make sure the document has been indexed first using index_document()."
        )
    
    # If debug mode, show retrieved context
    if debug:
        await debug_query(doc_id, query, mode=mode, **query_kwargs)
    
    # Perform the query
    # Use aquery (async) instead of query (sync) when already in async context
    # This avoids "This event loop is already running" errors
    if hasattr(rag, 'aquery'):
        response = await rag.aquery(
            query=query,
            mode=mode,
            **query_kwargs
        )
    else:
        # Fallback to sync query if aquery not available
        response = rag.query(
            query=query,
            mode=mode,
            **query_kwargs
        )
    
    return response


async def debug_query(
    doc_id: str,
    query: str,
    *,
    mode: str = "mix",
    **query_kwargs
) -> None:
    """
    Debug a query by showing retrieved chunks before generating an answer.
    
    This function prints out the context that would be used for answering
    the query, without actually generating the final answer.
    
    Args:
        doc_id: Document ID to query
        query: Question or query text
        mode: Query mode (default: "mix")
        **query_kwargs: Additional query parameters
    """
    from raganything.query import QueryParam
    
    if not doc_id:
        raise ValueError("doc_id cannot be empty")
    
    if not query:
        raise ValueError("query cannot be empty")
    
    rag = get_rag_instance_for_doc(doc_id)
    
    if rag is None:
        raise ValueError(
            f"No RAG instance found for doc_id: {doc_id}. "
            "Make sure the document has been indexed first using index_document()."
        )
    
    # Create query parameters
    query_param = QueryParam(
        query=query,
        mode=mode,
        **query_kwargs
    )
    
    # Retrieve context (this is what RAG uses internally)
    # Access the underlying LightRAG instance
    if hasattr(rag, 'lightrag') and rag.lightrag:
        lightrag = rag.lightrag
        
        # Get retrieved nodes/context
        # The exact API depends on LightRAG implementation
        # This is a simplified version - actual implementation may vary
        print(f"\n{'='*80}")
        print(f"Debug Query for doc_id: {doc_id}")
        print(f"Query: {query}")
        print(f"Mode: {mode}")
        print(f"{'='*80}\n")
        
        # Try to get retrieval results
        try:
            # This is a placeholder - actual LightRAG API may differ
            # The goal is to show what context was retrieved
            print("Retrieved context information:")
            print("(Note: Actual context retrieval depends on LightRAG API)")
            print("\nTo see actual retrieved chunks, check the RAG-Anything query implementation.")
        except Exception as e:
            print(f"Could not retrieve debug info: {e}")
        
        print(f"{'='*80}\n")

